[shell]
program = "/usr/local/bin/fish"
args = ["-l","-c","tmux a -t base || tmux new -s base"]

[window]
dynamic_title = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "Monaco Nerd Font"
size = 12

[colors.primary]
background = "#222327"
foreground = "#E2E2E3"
