[shell]
program = "/usr/local/bin/fish"
args = ["-l","-c","tmux a -t base || tmux new -s base"]

[window]
dynamic_title = true
dynamic_padding = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "Monaco Nerd Font"
size = 12
offset.x = 0
offset.y = 0

[colors.primary]
background = "#222327"
foreground = "#e2e2e3"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#85d3f2"
white = "#e2e2e3"
