-- local ls = require("luasnip")
-- local extras = require("luasnip.extras")
--
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local rep = extras.rep
--
-- local snippets
--
-- snippets = {
--   s("bindf", {
--     t("this"), i(1), t(" = this"), rep(1), t(".bind(this);")
--   }),
-- }
--
-- ls.add_snippets("javascript", snippets)
-- ls.add_snippets("typescript", snippets)
-- ls.add_snippets("javascriptreact", snippets)
-- ls.add_snippets("typescriptreact", snippets)
